{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"1_Python_Ders_1_26_04_2021_Bireysel_Calısma.ipynb","provenance":[],"collapsed_sections":[],"authorship_tag":"ABX9TyPHr/MTz4FgzuvXKp47zbi5"},"kernelspec":{"name":"python3","display_name":"Python 3.9.4 64-bit"},"language_info":{"name":"python","version":"3.9.4"},"interpreter":{"hash":"78f499e638b180260314974c742cd0103cf7e397c22b4021a02426f6fead37c4"}},"cells":[{"cell_type":"code","metadata":{"id":"nrNp3uI-r8h-","executionInfo":{"status":"ok","timestamp":1619482986613,"user_tz":-180,"elapsed":2150,"user":{"displayName":"Engin Caliskan","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjCeifJ5R545-4cHpCmPWCbs_hlOVRMUf_2yws1=s64","userId":"05516304192861072594"}}},"source":["# 12_Python+_Ders_12_Exception_Handling_11_06_2021"],"execution_count":1,"outputs":[]},{"cell_type":"code","execution_count":2,"metadata":{},"outputs":[],"source":["# Exception Handling"]},{"cell_type":"code","execution_count":4,"metadata":{},"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"division by zero","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[1;32m<ipython-input-4-5f354ceb437f>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      3\u001b[0m     \u001b[0mno_one\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minput\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"The first number please : \"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m     \u001b[0mno_two\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minput\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"The second number please : \"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 5\u001b[1;33m     \u001b[0mdivision\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mno_one\u001b[0m \u001b[1;33m/\u001b[0m \u001b[0mno_two\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      6\u001b[0m     \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"The result of the division is : \"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdivision\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      7\u001b[0m     \u001b[1;32mbreak\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"]}],"source":["# ZeroDivisionError: division by zero\n","while True:\n","    no_one = int(input(\"The first number please : \"))\n","    no_two = int(input(\"The second number please : \"))\n","    division = no_one / no_two\n","    print(\"The result of the division is : \", division)\n","    break"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["try:\n","    code block to be normally executed\n","except:\n","    code block to be exceptionally executed"]},{"cell_type":"code","execution_count":6,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["Something went wrong...Try again.\n","The result of the division is :  0.8\n"]}],"source":["while True:\n","    no_one = int(input(\"The first number please : \"))\n","    no_two = int(input(\"The second number please : \"))\n","    try:\n","        division = no_one / no_two\n","        print(\"The result of the division is : \", division)\n","        break\n","    except:\n","        print(\"Something went wrong...Try again.\")\n","# first input is zero"]},{"cell_type":"code","execution_count":7,"metadata":{},"outputs":[],"source":["# Of course, when do this, we anticipate which exception error we will encounter."]},{"cell_type":"code","execution_count":8,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["You can't divide by zero! Try again.\n","The result of the division is :  0.8\n"]}],"source":["while True:\n","    no_one = int(input(\"The first number please : \"))\n","    no_two = int(input(\"The second number please : \"))\n","    try:\n","        division = no_one / no_two\n","        print(\"The result of the division is : \", division)\n","        break\n","    except ZeroDivisionError:\n","        print(\"You can't divide by zero! Try again.\")\n","# first input is zero"]},{"cell_type":"code","execution_count":1,"metadata":{},"outputs":[],"source":["# Full 'Exception Handling Block'"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["try :\n","    statement\n","    ...\n","except :\n","    statement\n","    ...\n","else :\n","    statement\n","    ...\n","finally :\n","    statement\n","    ..."]},{"cell_type":"code","execution_count":2,"metadata":{},"outputs":[],"source":["# executes all statements between try and except\n","# no exception, then the try block is successfully executed and finished\n","# If an exception raises, the rest of the try block is ignored\n","# checks if the type of exception matches the exception specified\n","# executes the except block and resumes executing the program after the try-except block\n","# exception doesn’t match the exception named in the except syntax, execution of your program stops with a traceback error message.\n","# else-block is only executed if there raised no exceptions.\n","# finally syntax is always executed before leaving the try-except block, whether an exception was raised or not"]},{"cell_type":"code","execution_count":3,"metadata":{},"outputs":[],"source":[" # Handling Exception : https://docs.python.org/3/tutorial/errors.html#handling-exceptions"]},{"cell_type":"code","execution_count":4,"metadata":{},"outputs":[],"source":["# Implementation of the Full 'Exception Handling Block'-1"]},{"cell_type":"code","execution_count":5,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["The result of the division is :  0.8\nThanks for using our mini divison calculator! Come again!\n"]}],"source":["while True:\n","    no_one = int(input(\"The first number please : \"))\n","    no_two = int(input(\"The second number please : \"))\n","    try:\n","        division = no_one / no_two  # normal part of the program\n","    except ZeroDivisionError:\n","        print(\"You can't divide by zero! Try again.\")  # executes when division by zero\n","    else:\n","        print(\"The result of the division is : \", division)  # executes if there is no exception\n","    finally:\n","        print(\"Thanks for using our mini divison calculator! Come again!\")\n","        break  # exits the while loop"]},{"cell_type":"code","execution_count":6,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["You can't divide by zero! Try again.\nThanks for using our mini divison calculator! Come again!\n"]}],"source":["while True:\n","    no_one = int(input(\"The first number please : \"))\n","    no_two = int(input(\"The second number please : \"))\n","    try:\n","        division = no_one / no_two  # normal part of the program\n","    except ZeroDivisionError:\n","        print(\"You can't divide by zero! Try again.\")  # executes when division by zero\n","    else:\n","        print(\"The result of the division is : \", division)  # executes if there is no exception\n","    finally:\n","        print(\"Thanks for using our mini divison calculator! Come again!\")\n","        break  # exits the while loop"]},{"cell_type":"code","execution_count":7,"metadata":{},"outputs":[{"output_type":"error","ename":"ValueError","evalue":"invalid literal for int() with base 10: 'p'","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[1;32m<ipython-input-7-5fd297d1c219>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;32mwhile\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m     \u001b[0mno_one\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minput\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"The first number please : \"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m     \u001b[0mno_two\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minput\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"The second number please : \"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      4\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m         \u001b[0mdivision\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mno_one\u001b[0m \u001b[1;33m/\u001b[0m \u001b[0mno_two\u001b[0m  \u001b[1;31m# normal part of the program\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;31mValueError\u001b[0m: invalid literal for int() with base 10: 'p'"]}],"source":["while True:\n","    no_one = int(input(\"The first number please : \"))\n","    no_two = int(input(\"The second number please : \"))\n","    try:\n","        division = no_one / no_two  # normal part of the program\n","    except ZeroDivisionError:\n","        print(\"You can't divide by zero! Try again.\")  # executes when division by zero\n","    else:\n","        print(\"The result of the division is : \", division)  # executes if there is no exception\n","    finally:\n","        print(\"Thanks for using our mini divison calculator! Come again!\")\n","        break  # exits the while loop"]},{"cell_type":"code","execution_count":8,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["Something went wrong...Try again.\nProbably it is because of 'division by zero' error\n"]}],"source":["while True:\n","    no_one = int(input(\"The first number please : \"))\n","    no_two = int(input(\"The second number please : \"))\n","    try:\n","        division = no_one / no_two\n","        print(\"The result of the division is : \", division)\n","        break\n","    except Exception as e:\n","        print(\"Something went wrong...Try again.\")\n","        print(\"Probably it is because of '{}' error\".format(e))\n","        break"]},{"cell_type":"code","execution_count":9,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["The error message is :  name 'c' is not defined\n"]}],"source":["try :\n","    a = 10\n","    b = 2\n","    print(\"The result of division is :\", c)\n","except Exception as e:\n","    print(\"The error message is : \", e)"]},{"cell_type":"code","execution_count":10,"metadata":{},"outputs":[],"source":["# it raised a NameError of which associated value is displayed in the output cell above : \"name 'c' is not defined\"."]},{"cell_type":"code","execution_count":11,"metadata":{},"outputs":[],"source":["# Apart from GeneratorExit, KeyboardInterrupt, SystemExit, the Exception keyword you learned in the previous lesson covers all exceptions."]},{"cell_type":"code","execution_count":12,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["Hello\nNothing is wrong\n"]}],"source":["\ttry:\n","\t  print(\"Hello\")\n","\texcept:\n","\t  print(\"Something is wrong\")\n","\telse:\n","  print(\"Nothing is wrong\")"]},{"cell_type":"code","execution_count":13,"metadata":{},"outputs":[],"source":["# Implementation of the Full 'Exception Handling Block'-2"]},{"cell_type":"code","execution_count":14,"metadata":{},"outputs":[],"source":["# The else clause is executed only if no exceptions are raised."]},{"cell_type":"code","execution_count":15,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["Nothing went wrong\n"]}],"source":["try:\n","    x = 4 / 1\n","except:\n","    print('Something went wrong')\n","else:\n","    print('Nothing went wrong')"]},{"cell_type":"code","execution_count":16,"metadata":{},"outputs":[],"source":["# The finally clause is always executed, whether an exception has occurred or not."]},{"cell_type":"code","execution_count":17,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["Something went wrong\nAlways execute this\n"]}],"source":["try:\n","\tx = 3 / 0\n","except:\n","\tprint('Something went wrong')\n","finally:\n","\tprint('Always execute this')\n"]},{"cell_type":"code","execution_count":20,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["Something went wrong\n"]},{"output_type":"error","ename":"NameError","evalue":"name 'f' is not defined","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[1;32m<ipython-input-20-782ed6471f81>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      5\u001b[0m     \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Something went wrong\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 7\u001b[1;33m     \u001b[0mf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mclose\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[1;31mNameError\u001b[0m: name 'f' is not defined"]}],"source":["try:\n","    f = open('myfile.txt')\n","    print(f.read())\n","except:\n","    print(\"Something went wrong\")\n","finally:\n","    f.close()\n"]},{"cell_type":"code","execution_count":22,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["An exception occurred\n"]}],"source":["try:\n","  print(y)\n","except:\n","  print(\"An exception occurred\")"]},{"cell_type":"code","execution_count":23,"metadata":{},"outputs":[],"source":["# Several Handling Scenarios"]},{"cell_type":"code","execution_count":24,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["Attempt to divide by zero\n"]}],"source":["try:\n","    x = 2/0\n","except ZeroDivisionError:\n","    print('Attempt to divide by zero')\n","except:\n","    print('Something else went wrong')"]},{"cell_type":"code","execution_count":30,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["Unknown exception error occured. Tyr again please.\n"]}],"source":["try:\n","    x = 2/trt\n","except:\n","    print(\"Unknown exception error occured. Tyr again please.\")"]},{"cell_type":"code","execution_count":35,"metadata":{},"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-35-3196879959e9>, line 2)","traceback":["\u001b[1;36m  File \u001b[1;32m\"<ipython-input-35-3196879959e9>\"\u001b[1;36m, line \u001b[1;32m2\u001b[0m\n\u001b[1;33m    except ZeroDivisionError:\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"]}],"source":["...\n","except ZeroDivisionError:\n","   print(\"You can't divide by zero!!\")\n","except ValueError:\n","   print(\"You can only enter numbers consisting of digits, not text!!\")\n"]},{"cell_type":"code","execution_count":27,"metadata":{},"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-27-46ac54e88722>, line 1)","traceback":["\u001b[1;36m  File \u001b[1;32m\"<ipython-input-27-46ac54e88722>\"\u001b[1;36m, line \u001b[1;32m1\u001b[0m\n\u001b[1;33m    ....\u001b[0m\n\u001b[1;37m        ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"]}],"source":["....\n","except (ValueError, TypeError):\n","    print(\"You can only enter numbers consisting of digits, not text!!\")\n"]},{"cell_type":"code","execution_count":28,"metadata":{},"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-28-d6c1405c8922>, line 1)","traceback":["\u001b[1;36m  File \u001b[1;32m\"<ipython-input-28-d6c1405c8922>\"\u001b[1;36m, line \u001b[1;32m1\u001b[0m\n\u001b[1;33m    ....\u001b[0m\n\u001b[1;37m        ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"]}],"source":["....\n","except ArithmeticError:\n","    print(\"I will also catch OverflowError, FloatingPointError and ZeroDivisionError\")\n"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["# built-in exceptions are formed a hierarchical structure :\n","# https://docs.python.org/3/library/exceptions.html#exception-hierarchy"]},{"cell_type":"code","execution_count":29,"metadata":{},"outputs":[],"source":["# find all the built-in Python exceptions :\n","# https://docs.python.org/3/library/exceptions.html#built-in-exceptions"]},{"cell_type":"code","execution_count":36,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["Hello\nEverything is okay\n"]}],"source":["try:\n","  print(\"Hello\")\n","except:\n","  print(\"Something went wrong\")\n","else:\n","  print(\"Everything is okay\")"]},{"cell_type":"code","execution_count":38,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["Something is wrong\nThe 'try except' is completed\n"]}],"source":["try:\n","  print(z)\n","except:\n","  print(\"Something is wrong\")\n","finally:\n","  print(\"The 'try except' is completed\")"]},{"cell_type":"code","execution_count":39,"metadata":{},"outputs":[],"source":["# Exception errors are detected during the program [execution] (interpretation) process."]},{"cell_type":"code","execution_count":40,"metadata":{},"outputs":[],"source":["# Syntax errors are detected during [compiling] the program into byte-code."]},{"cell_type":"code","execution_count":41,"metadata":{},"outputs":[],"source":["# [NameError] is usually raised if a variable you use in the code stream is not pre-defined or not properly defined."]},{"cell_type":"code","execution_count":42,"metadata":{},"outputs":[],"source":["# [TypeError] is raised when an operation or function is applied to an object of inappropriate type."]},{"cell_type":"code","execution_count":43,"metadata":{},"outputs":[],"source":["# [ValueError] is raised when an operation or function receives an argument that has the right type but an inappropriate value."]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["# Complementary Video Lesson about Error and Exception Handling"]},{"cell_type":"code","execution_count":45,"metadata":{},"outputs":[],"source":["# Error Handling >>> Every enviromentals\n","# Debugging >>> Code Wrong"]},{"cell_type":"code","execution_count":46,"metadata":{},"outputs":[],"source":["# Errors\n","# 1. Syntax Errors\n","# 2. Runtime Errors\n","# 3. Logic Errors"]},{"cell_type":"code","execution_count":47,"metadata":{},"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-47-3caa01999347>, line 4)","traceback":["\u001b[1;36m  File \u001b[1;32m\"<ipython-input-47-3caa01999347>\"\u001b[1;36m, line \u001b[1;32m4\u001b[0m\n\u001b[1;33m    if x == y\u001b[0m\n\u001b[1;37m             ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"]}],"source":["# Syntax Errors\n","# This code will not run at all\n","x = 42\n","y = 206\n","if x == y\n","    print(\"Success\")"]},{"cell_type":"code","execution_count":48,"metadata":{},"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"division by zero","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[1;32m<ipython-input-48-f87b67c1ba65>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[0mx\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m42\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[0my\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 5\u001b[1;33m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mx\u001b[0m \u001b[1;33m/\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"]}],"source":["# Runtime Errors\n","# This code will fail when run\n","x = 42\n","y = 0\n","print(x / y)"]},{"cell_type":"code","execution_count":49,"metadata":{},"outputs":[{"output_type":"stream","name":"stdout","text":["Sorry, something went wrong\nThis always runs on success or failure\n"]}],"source":["# Catching Runtime Errors\n","x = 4\n","y = 0\n","try :\n","    print(x / y)\n","except ZeroDivisionError as e :\n","    # Optional, log e somewhere\n","    print(\"Sorry, something went wrong\")\n","except :\n","    print(\"Something really went wrong\")\n","finally :\n","    print(\"This always runs on success or failure\")"]},{"cell_type":"code","execution_count":51,"metadata":{},"outputs":[],"source":["# Logic Errors\n","# This code won't run at all\n","x = 206\n","y = 42\n","if x < y :\n","    print(str(x) + \"is greater than\" + str(y))"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":[]}]}